import {
  GITHUB_URL,
  ICON_HEAD,
  SITE_HEAD,
} from "../../../packages/shared/site-meta";

// Content is server-authored HTML; callers must escape any user-supplied values.
export function accessPage(content: string, publicEntry = false) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${publicEntry ? SITE_HEAD : `<title>Your field pass · Coffee Under Fire</title><meta name="robots" content="noindex">${ICON_HEAD}`}<style>
*{box-sizing:border-box}body{margin:0;min-height:100svh;background:#24332a;color:#293b2e;font:16px/1.5 system-ui,-apple-system,sans-serif;padding:clamp(18px,4vw,56px);background-image:radial-gradient(ellipse at 10% 0%,#52604466,transparent 65%),repeating-linear-gradient(135deg,transparent 0 79px,#d3c69b06 80px 81px)}
main{max-width:1040px;margin:1vh auto;display:grid;grid-template-columns:1fr 1fr;gap:clamp(24px,5vw,64px);align-items:center}.story{color:#eee5c5;min-width:0}.logo{display:block;width:min(100%,350px);height:auto;margin:0 0 12px}.eyebrow{color:#d9bc77;text-transform:uppercase;font-size:11px;font-weight:750;letter-spacing:.17em}.story h1{font-size:clamp(32px,4vw,48px);line-height:1.08;letter-spacing:-.035em;max-width:12ch;margin:16px 0;text-wrap:balance}.intro{max-width:34ch;color:#c9d0bd;font-size:17px}.jev-note{border-left:3px solid #cdb174;padding:3px 0 3px 16px;margin:20px 0;max-width:36ch}.jev-note strong{display:block;color:#f3e8c8}.jev-note p{color:#c9d0bd;font-size:14px;margin:6px 0}.story nav{display:flex;flex-wrap:wrap;gap:12px 24px;font-size:14px}.story a{color:#e3c481;text-underline-offset:4px}.support{font-size:13px;color:#bfc9b4;margin-top:18px;max-width:40ch}.support p{margin:0 0 5px}
.pass{background:#eee5c5;padding:clamp(22px,3vw,36px);border-radius:8px 24px 8px 8px;box-shadow:10px 12px 0 #14261b80;min-width:0;border-top:5px solid #cfad68}.pass h2{font-size:28px;line-height:1.15;letter-spacing:-.025em;margin:8px 0 10px}.pass .eyebrow{color:#756039}.pass p{margin:10px 0 18px}.muted,small{color:#58624e;font-size:13px;line-height:1.5}label{display:block;font-size:14px;font-weight:650;margin:16px 0 6px}label small{font-weight:400}input{display:block;width:100%;min-width:0;padding:13px 14px;background:#fff9e7;color:#25372b;border:1px solid #919b7c;border-radius:5px;font:inherit;margin:6px 0 8px}input::placeholder{color:#79816d}button{width:100%;min-height:48px;background:#a64d28;color:#fff4d9;border:0;border-radius:5px;font:700 16px/1.2 system-ui;padding:14px 18px;cursor:pointer;margin-top:14px;transition:background .15s,transform .15s}button:hover{background:#873c1e}button:active{transform:translateY(1px)}a:hover{text-decoration-thickness:2px}:focus-visible{outline:3px solid #c9873e;outline-offset:4px}.pass a{color:#435a36;text-underline-offset:3px}.notice{background:#faefd4;border-left:4px solid #a64d28;padding:12px 14px;font-size:14px}.cf-turnstile{margin-top:16px;max-width:100%}details{border-top:1px solid #c6bc96;margin-top:22px;padding-top:16px}summary{cursor:pointer;font-weight:650;font-size:14px;min-height:30px}details p{font-size:13px}.reset{font-size:12px;color:#68705b;margin-top:20px!important}.pass footer{margin-top:18px;font-size:13px}.skip{position:absolute;left:-9999px}.skip:focus{left:20px;top:10px;background:#fff9e7;padding:8px;color:#24332a}
@media(max-width:740px){main{grid-template-columns:1fr;max-width:480px;margin:0 auto;gap:22px}.logo{width:230px;margin:0 auto 12px}.story h1{font-size:30px;max-width:none;text-align:center;margin:6px 0}.story>.eyebrow,.intro,.jev-note p,.support p{display:none}.support{text-align:center;margin-top:12px;max-width:none}.jev-note{border:0;margin:10px 0;text-align:center;max-width:none;padding:0;font-size:13px}.story nav{justify-content:center;font-size:13px;gap:18px}.pass{padding:22px}.pass h2{font-size:26px}}@media(max-width:380px){body{padding:12px 0}.story{padding:0 12px}.pass{padding:22px 10px;border-radius:0;box-shadow:none}}@media(prefers-reduced-motion:reduce){button{transition:none}}
</style></head><body><a class="skip" href="#entry">Skip to sign in</a><main><header class="story"><a href="/" aria-label="Coffee Under Fire home"><img class="logo" src="/assets/brand/coffee-under-fire-logo-v1.png" width="1774" height="887" alt="Coffee Under Fire"></a><span class="eyebrow">A little coffee. A lot of trouble.</span><h1>Hold the line.<br>Keep it brewing.</h1><p class="intro">Dodge enemy fire, collect upgrades, and get a hot cup to the general.</p><aside class="jev-note"><strong>NPC tactics powered by Jev</strong><p>TypeSafe AI’s Jev model chooses the tactics. You bring the coffee.</p></aside><nav aria-label="Project links"><a href="/leaderboard">Field honours ↗</a><a href="${GITHUB_URL}" target="_blank" rel="noopener noreferrer">☆ Star on GitHub</a></nav><aside class="support"><p>The general gets the coffee. The developer gets the API bill.</p><a href="https://ko-fi.com/thepolyglotprogrammer" target="_blank" rel="noopener noreferrer">Buy the developer a coffee ↗</a><p>Optional support. No gameplay perks.</p></aside></header><section class="pass" id="entry" aria-label="Enter the outpost">${content}</section></main></body></html>`;
}
